### ISSUE TITLE
UnboundLocalError: local variable 'from_heuristic' referenced before assignment

### ISSUE THREAD

**Issue by jeandet** [FFY00/meson-python#118]
Hello,

Installing a package with `pip install .` seems to produce the following error on both OSX and Linux (tested with latest pip(22.2) and mesonpy (0.8.0)):
```BASH
    File "/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
      hook = backend.prepare_metadata_for_build_wheel
  AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
      whl_basename = backend.build_wheel(metadata_directory, config_settings)
    File "/tmp/pip-build-env-xctgyvsg/overlay/local/lib/python3.10/site-packages/mesonpy/__init__.py", line 941, in build_wheel
      return project.wheel(out).name
    File "/tmp/pip-build-env-xctgyvsg/overlay/local/lib/python3.10/site-packages/mesonpy/__init__.py", line 889, in wheel
      wheel = _WheelBuilder(self).build(self._install_plan, self._copy_files, self._build_dir)
    File "/tmp/pip-build-env-xctgyvsg/overlay/local/lib/python3.10/site-packages/mesonpy/__init__.py", line 356, in build
      wheel_file = pathlib.Path(directory, f'{self.name}.whl')
    File "/tmp/pip-build-env-xctgyvsg/overlay/local/lib/python3.10/site-packages/mesonpy/__init__.py", line 165, in name
      python_tag=self._project.python_tag,
    File "/tmp/pip-build-env-xctgyvsg/overlay/local/lib/python3.10/site-packages/mesonpy/__init__.py", line 657, in python_tag
      selected_tag = self._select_abi_tag()
    File "/tmp/pip-build-env-xctgyvsg/overlay/local/lib/python3.10/site-packages/mesonpy/__init__.py", line 793, in _select_abi_tag
      tags = self._files_by_tag()
    File "/tmp/pip-build-env-xctgyvsg/overlay/local/lib/python3.10/site-packages/mesonpy/__init__.py", line 775, in _files_by_tag
      if from_heuristic:
  UnboundLocalError: local variable 'from_heuristic' referenced before assignment
```
moving this line https://github.com/FFY00/meson-python/blob/main/mesonpy/__init__.py#L764 to https://github.com/FFY00/meson-python/blob/main/mesonpy/__init__.py#L747 seems to `work`.  Not sure this is actually a fix. 
I also have an issue (maybe related) where mesonpy isn't able to see that [my package](https://github.com/SciQLop/CDFpp/blob/main/meson.build#L104) isn't pure and suffix all wheels by `any` instead of specific platform tags. This is really weird because this package is actually C++ only.

I say this could be related since mesonpy seems to fail with the same set of variables https://github.com/FFY00/meson-python/blob/main/mesonpy/__init__.py#L641

**Comment by FFY00** [comment]
Should be fixed by https://github.com/FFY00/meson-python/releases/tag/0.8.1. I will yank 0.8.0 from PyPI.
