### ISSUE TITLE
Backend dependency issue: patchelf-wrapper not found

### ISSUE THREAD

**Issue by rgommers** [FFY00/meson-python#52]
I don't immediately see what is going on here, but it's a bug in `meson-python` I think. Apply this patch on top of SciPy's main branch:
```diff
diff --git a/pyproject.toml b/pyproject.toml
index 1b44bc54e..f5c49aab6 100644
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -8,7 +8,9 @@
 #     "pybind11>=2.4.3,<2.5.0",
 
 [build-system]
+build-backend = 'mesonpy'
 requires = [
+    "meson-python>=0.4.0",
     "wheel",
     "setuptools<60.0",  # do not increase, 60.0 enables vendored distutils
     "Cython>=0.29.18",
```

Then `pip install .` is very unhappy (on Arch Linux, in the standard `scipy-dev` conda env):
```
$ pip install .
Processing /home/rgommers/code/bldscipy
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      ERROR: Could not find a version that satisfies the requirement patchelf-wrapper (from versions: none)
      ERROR: No matching distribution found for patchelf-wrapper
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Verbose `pip` output in case it helps:

<details>

```
$ conda activate scipy-dev
$ pip install . -v -v -v
Using pip 22.0.4 from /home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pip (python 3.10)
Non-user install because site-packages writeable
Created temporary directory: /tmp/pip-ephem-wheel-cache-0b47_ica
Created temporary directory: /tmp/pip-req-tracker-1y9qcxgd
Initialized build tracking at /tmp/pip-req-tracker-1y9qcxgd
Created build tracker: /tmp/pip-req-tracker-1y9qcxgd
Entered build tracker: /tmp/pip-req-tracker-1y9qcxgd
Created temporary directory: /tmp/pip-install-25kkp9xi
Processing /home/rgommers/code/bldscipy
  Added file:///home/rgommers/code/bldscipy to build tracker '/tmp/pip-req-tracker-1y9qcxgd'
  Created temporary directory: /tmp/pip-build-env-wo_jvcsn
  Created temporary directory: /tmp/pip-standalone-pip-d6a02_yy
  Running command pip subprocess to install build dependencies
  Using pip 22.0.4 from /tmp/pip-standalone-pip-d6a02_yy/__env_pip__.zip/pip (python 3.10)
  Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "aarch64" and platform_python_implementation != "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.8" and platform_machine == "arm64" and platform_system == "Darwin"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.9" and platform_machine == "arm64" and platform_system == "Darwin"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.8" and (platform_machine != "arm64" or platform_system != "Darwin") and platform_machine != "aarch64" and platform_python_implementation != "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version == "3.9" and (platform_machine != "arm64" or platform_system != "Darwin") and platform_python_implementation != "PyPy"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.11"' don't match your environment
  Ignoring numpy: markers 'python_version >= "3.8" and platform_python_implementation == "PyPy"' don't match your environment
  Collecting meson-python>=0.4.0
    Using cached meson_python-0.4.0-py3-none-any.whl (14 kB)
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Collecting setuptools<60.0
    Using cached setuptools-59.8.0-py3-none-any.whl (952 kB)
  Collecting Cython>=0.29.18
    Using cached Cython-0.29.28-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (1.9 MB)
  Collecting pybind11>=2.4.3
    Using cached pybind11-2.9.2-py2.py3-none-any.whl (213 kB)
  Collecting pythran>=0.9.12
    Using cached pythran-0.11.0-py3-none-any.whl (4.2 MB)
  Collecting numpy==1.21.4
    Using cached numpy-1.21.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (15.9 MB)
  Collecting tomli>=1.0.0
    Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
  Collecting ninja
    Using cached ninja-1.10.2.3-py2.py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.whl (108 kB)
  Collecting meson>=0.60.0
    Using cached meson-0.62.1-py3-none-any.whl (863 kB)
  Collecting ply>=3.4
    Using cached ply-3.11-py2.py3-none-any.whl (49 kB)
  Collecting beniget~=0.4.0
    Using cached beniget-0.4.1-py3-none-any.whl (9.4 kB)
  Collecting gast~=0.5.0
    Using cached gast-0.5.3-py3-none-any.whl (19 kB)
  Installing collected packages: ply, ninja, wheel, tomli, setuptools, pybind11, numpy, meson, gast, Cython, meson-python, beniget, pythran
    Creating /tmp/pip-build-env-wo_jvcsn/overlay/bin
    changing mode of /tmp/pip-build-env-wo_jvcsn/overlay/bin/ninja to 755
    changing mode of /tmp/pip-build-env-wo_jvcsn/overlay/bin/wheel to 755
    changing mode of /tmp/pip-build-env-wo_jvcsn/overlay/bin/pybind11-config to 755
    changing mode of /tmp/pip-build-env-wo_jvcsn/overlay/bin/f2py to 755
    changing mode of /tmp/pip-build-env-wo_jvcsn/overlay/bin/f2py3 to 755
    changing mode of /tmp/pip-build-env-wo_jvcsn/overlay/bin/f2py3.10 to 755
    changing mode of /tmp/pip-build-env-wo_jvcsn/overlay/bin/meson to 755
    changing mode of /tmp/pip-build-env-wo_jvcsn/overlay/bin/cygdb to 755
    changing mode of /tmp/pip-build-env-wo_jvcsn/overlay/bin/cython to 755
    changing mode of /tmp/pip-build-env-wo_jvcsn/overlay/bin/cythonize to 755
    changing mode of /tmp/pip-build-env-wo_jvcsn/overlay/bin/pythran to 755
    changing mode of /tmp/pip-build-env-wo_jvcsn/overlay/bin/pythran-config to 755
  Successfully installed Cython-0.29.28 beniget-0.4.1 gast-0.5.3 meson-0.62.1 meson-python-0.4.0 ninja-1.10.2.3 numpy-1.21.4 ply-3.11 pybind11-2.9.2 pythran-0.11.0 setuptools-59.8.0 tomli-2.0.1 wheel-0.37.1
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  The Meson build system
  Version: 0.62.1
  Source dir: /home/rgommers/code/bldscipy
  Build dir: /home/rgommers/code/bldscipy/.mesonpy-7ry9fiku/build
  Build type: native build
  Project name: SciPy
  Project version: 1.9.0.dev0
  C compiler for the host machine: /home/rgommers/anaconda3/envs/scipy-dev/bin/x86_64-conda-linux-gnu-cc (gcc 9.4.0 "x86_64-conda-linux-gnu-cc (GCC) 9.4.0")
  C linker for the host machine: /home/rgommers/anaconda3/envs/scipy-dev/bin/x86_64-conda-linux-gnu-cc ld.bfd 2.36.1
  C++ compiler for the host machine: /home/rgommers/anaconda3/envs/scipy-dev/bin/x86_64-conda-linux-gnu-c++ (gcc 9.4.0 "x86_64-conda-linux-gnu-c++ (GCC) 9.4.0")
  C++ linker for the host machine: /home/rgommers/anaconda3/envs/scipy-dev/bin/x86_64-conda-linux-gnu-c++ ld.bfd 2.36.1
  Host machine cpu family: x86_64
  Host machine cpu: x86_64
  Compiler for C supports arguments -Wno-unused-but-set-variable: YES
  Library m found: YES
  Fortran compiler for the host machine: /home/rgommers/anaconda3/envs/scipy-dev/bin/x86_64-conda-linux-gnu-gfortran (gcc 9.4.0 "GNU Fortran (GCC) 9.4.0")
  Fortran linker for the host machine: /home/rgommers/anaconda3/envs/scipy-dev/bin/x86_64-conda-linux-gnu-gfortran ld.bfd 2.36.1
  Program cython found: YES (/tmp/pip-build-env-wo_jvcsn/overlay/bin/cython)
  Program pythran found: YES (/tmp/pip-build-env-wo_jvcsn/overlay/bin/pythran)
  Program cp found: YES (/usr/bin/cp)
  Program python3 found: YES (/home/rgommers/anaconda3/envs/scipy-dev/bin/python3.10)
  Found pkg-config: /home/rgommers/anaconda3/envs/scipy-dev/bin/pkg-config (0.29.2)
  Library npymath found: YES
  Library npyrandom found: YES
  Run-time dependency openblas found: YES 0.3.18
  Dependency openblas found: YES 0.3.18 (cached)
  Program _build_utils/cythoner.py found: YES (/home/rgommers/anaconda3/envs/scipy-dev/bin/python3.10 /home/rgommers/code/bldscipy/scipy/_build_utils/cythoner.py)
  Checking for function "open_memstream" : NO
  Configuring messagestream_config.h using configuration
  Checking for size of "void*" : 8
  Run-time dependency threads found: YES
  Checking for size of "void*" : 8
  Dependency threads found: YES unknown (cached)
  Compiler for C supports arguments -Wno-unused-but-set-variable: YES (cached)
  Compiler for C supports arguments -Wno-unused-but-set-variable: YES (cached)
  Compiler for C++ supports arguments -Wno-format-truncation: YES
  Compiler for C++ supports arguments -Wno-class-memaccess: YES
  Build targets in project: 199

  SciPy 1.9.0.dev0

    User defined options
      Native files: /home/rgommers/code/bldscipy/.mesonpy-native-file.ini
      debug       : false
      optimization: 2
      prefix      : /home/rgommers/anaconda3/envs/scipy-dev
      strip       : true

  Found ninja-1.10.2.git.kitware.jobserver-1 at /tmp/pip-build-env-wo_jvcsn/overlay/bin/ninja
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_lib_pxd' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_lib_pxd' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_ufuncs_pxi_pxd' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_ufuncs_pxi_pxd' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_ufuncs_pxi_pxd' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_ufuncs_pxi_pxd' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target 'cython_linalg' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target 'cython_linalg' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target 'cython_linalg' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target 'cython_linalg' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_ufuncs_pxi_pxd' has more than one output! Using the first one.
  WARNING: custom_target '_stats_pxd' has more than one output! Using the first one.
  WARNING: custom_target 'cython_special' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_stats_gen_pyx' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_stats_gen_pyx' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_stats_gen_pyx' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_stats_gen_pyx' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_stats_gen_pyx' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_lib_pxd' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_spatial_pxd' has more than one output! Using the first one.
  WARNING: custom_target '_lib_pxd' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target 'cython_linalg' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target 'cython_linalg' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target 'cython_linalg' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_spatial_pxd' has more than one output! Using the first one.
  WARNING: custom_target '_lib_pxd' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target 'cython_linalg' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target 'cython_linalg' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target 'cython_linalg' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_lib_pxd' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_dummy_init_cyoptimize' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  WARNING: custom_target '_cython_tree' has more than one output! Using the first one.
  + meson setup --native-file=/home/rgommers/code/bldscipy/.mesonpy-native-file.ini -Ddebug=false -Dstrip=true -Doptimization=2 --prefix=/home/rgommers/anaconda3/envs/scipy-dev /home/rgommers/code/bldscipy /home/rgommers/code/bldscipy/.mesonpy-7ry9fiku/build
  Getting requirements to build wheel ... done
  Created temporary directory: /tmp/pip-standalone-pip-al_orp3p
  Running command pip subprocess to install backend dependencies
  Using pip 22.0.4 from /tmp/pip-standalone-pip-al_orp3p/__env_pip__.zip/pip (python 3.10)
  Collecting pep621>=0.3.0
    Using cached pep621-0.4.0-py3-none-any.whl (6.4 kB)
  ERROR: Could not find a version that satisfies the requirement patchelf-wrapper (from versions: none)
  ERROR: No matching distribution found for patchelf-wrapper
  error: subprocess-exited-with-error
  
  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/rgommers/anaconda3/envs/scipy-dev/bin/python3.10 /tmp/pip-standalone-pip-al_orp3p/__env_pip__.zip/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-wo_jvcsn/normal --no-warn-script-location -v --no-binary :none: --only-binary :all: -i https://pypi.org/simple -- 'pep621 >= 0.3.0' patchelf-wrapper
  cwd: [inherit]
  Installing backend dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Exception information:
Traceback (most recent call last):
  File "/home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 339, in run
    requirement_set = resolver.resolve(
  File "/home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 75, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
  File "/home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 506, in collect_root_requirements
    req = self._make_requirement_from_install_req(
  File "/home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 468, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
  File "/home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 288, in __init__
    super().__init__(
  File "/home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
    self.dist = self._prepare()
  File "/home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
    dist = self._prepare_distribution()
  File "/home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 299, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 487, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 556, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 58, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "/home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 45, in prepare_distribution_metadata
    self._install_build_reqs(finder)
  File "/home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pip/_internal/distributions/sdist.py", line 108, in _install_build_reqs
    self.req.build_env.install_requirements(
  File "/home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pip/_internal/build_env.py", line 202, in install_requirements
    self._install_requirements(
  File "/home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pip/_internal/build_env.py", line 260, in _install_requirements
    call_subprocess(
  File "/home/rgommers/anaconda3/envs/scipy-dev/lib/python3.10/site-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
    raise error
pip._internal.exceptions.InstallationSubprocessError: pip subprocess to install backend dependencies exited with 1
Removed file:///home/rgommers/code/bldscipy from build tracker '/tmp/pip-req-tracker-1y9qcxgd'
Removed build tracker: '/tmp/pip-req-tracker-1y9qcxgd'
```

</details>

**Comment by rgommers** [comment]
Hmm no, it's not installable on Python 3.8 and 3.9 either. https://pypi.org/project/patchelf-wrapper does have a tarball, but somehow Pip refuses to find it. I don't understand the dependency though, it's abandonware - while https://pypi.org/project/patchelf/ seems well-maintained.

**Comment by rgommers** [comment]
You can reproduce the same error with a simple `pip install patchelf-wrapper`

**Comment by rgommers** [comment]
`patchelf-wrapper`: will look for `patchelf` on the system and not install anything, that's why @FFY00 chose it.

**Comment by rgommers** [comment]
@FFY00 will look at which packages will actually need it (based on build files), and then inject only `patchelf` (not `patchelf-wrapper`). If not, then make it optional right now.
