### ISSUE TITLE
New meson-python break in SciPy 

### ISSUE THREAD

**Issue by rgommers** [FFY00/meson-python#79]
`pip install .` into a venv is completely broken, starting from about 6 hours ago. It looks like that's when https://pypi.org/project/pep621/0.4.0.post1/ was released, which seems like the likely culprit.

Full test log: https://github.com/scipy/scipy/runs/6836045634?check_suite_focus=true

```
  + meson setup --native-file=/home/runner/work/scipy/scipy/.mesonpy-native-file.ini -Ddebug=false -Dstrip=true -Doptimization=2 --prefix=/opt/hostedtoolcache/Python/3.10.4/x64 /home/runner/work/scipy/scipy /home/runner/work/scipy/scipy/.mesonpy-gh4z102y/build
  Traceback (most recent call last):
    File "/home/runner/work/scipy/venvs/scipy-venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/runner/work/scipy/venvs/scipy-venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/runner/work/scipy/venvs/scipy-venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-yj0sq7yp/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 805, in get_requires_for_build_wheel
      with _project(config_settings) as project:
    File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/contextlib.py", line 135, in __enter__
      return next(self.gen)
    File "/tmp/pip-build-env-yj0sq7yp/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 784, in _project
      with Project.with_temp_working_dir(
    File "/opt/hostedtoolcache/Python/3.10.4/x64/lib/python3.10/contextlib.py", line 135, in __enter__
      return next(self.gen)
    File "/tmp/pip-build-env-yj0sq7yp/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 479, in with_temp_working_dir
      yield cls(source_dir, tmpdir, build_dir)
    File "/tmp/pip-build-env-yj0sq7yp/overlay/lib/python3.10/site-packages/mesonpy/__init__.py", line 430, in __init__
      self._metadata.dynamic.remove('version')
  ValueError: list.remove(x): x not in list
  error: subprocess-exited-with-error
```

**Comment by FFY00** [comment]
Ugh, it seems 0.4.0.post1 was released from the wrong branch for some reason. I will yank it later and fix it, but a new meson-python release should also fix it with #70.
